version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: "/myapp/docker-credentials/username"
    DOCKER_REGISTRY_PASSWORD: "/myapp/docker-credentials/password"
    DOCKER_REGISTRY_URL: "/myapp/docker-registry/url"

phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - pip3 install -r aws-cicd/simple-python-app/requirements.txt
  build:
    commands:
      - cd aws-cicd/simple-python-app/
      - echo "building docker image"
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
      - docker build -t "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/demo-python-app:latest" .
      - docker push "docker.io/<docker_username>/demo-python-app:latest"
  post_build:
    commands:
      - echo "build is successfull"
